server:
  port: 8888
  context-path: /config

eureka:
  instance:
    hostname: localhost
    appname: github-config-service
    virtualHostName: github-config-service
    appGroupName: default-group
    preferIpAddress: true
    virtual-host-name: github-config-service
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
  client:
    region: default
    registryFetchIntervalSeconds: 5
    availabilityZones:
      default: ${APPLICATION_DOMAIN:${DOMAIN:defaultZone}}
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/discovery/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: http://172.28.4.241/stash/scm/chan/loving-service-config.git
          username: hanmin
          password: HAN42728926+min
          searchPaths: applications,wsapidoc


