server:
  port: 19300
  context-path: /config

eureka:
  instance:
    hostname: localhost
    appname: config-service
    virtualHostName: config-service
    #appGroupName: default-group
    preferIpAddress: true
    virtual-host-name: config-service
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
  client:
    region: default
    registryFetchIntervalSeconds: 5
    availabilityZones:
      default: ${APPLICATION_DOMAIN:${DOMAIN:defaultZone}}
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/discovery/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: http://sys@192.168.191.58:55002/git/changhongit.git
          username: sys
          password: sys
          searchPaths: wsapidoc,applications