server:
  port: 8761
  context-path: /discovery
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:${server.port}/discovery/eureka/

spring:
  cloud:
    config:
      discovery:
        enabled: true