server:
  port: 8761
  context-path: /discovery
eureka:
  instance:
    hostname: localhost
    appname: discovery-service
    preferIpAddress: false
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    registrySyncRetries: 3
    enableSelfPreservation: false

spring:
  thymeleaf:
    enabled: false
  cloud:
    config:
      discovery:
        enabled: true